# Generated by Django 4.2.3 on 2023-07-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChoice',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='LessonQuestion',
            new_name='Question',
        ),
    ]
