# Generated by Django 4.2.3 on 2023-07-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_options_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['total_correct_answers']},
        ),
    ]
