# Generated by Django 4.2.3 on 2023-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_created_question_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
