# Generated by Django 4.2.3 on 2023-07-06 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_scorerecord_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
