# Generated by Django 4.2.3 on 2023-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_scorerecord_percentage_alter_scorerecord_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorerecord',
            old_name='player',
            new_name='player_verified',
        ),
        migrations.RemoveField(
            model_name='scorerecord',
            name='player_nickname',
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='player_unverified',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
