# Generated by Django 4.2.3 on 2023-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_quiz_difficulty_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('General Knowledge', 'General Knowledge'), ('Sports', 'Sports'), ('Science', 'Science'), ('Others', 'Others')], default='Others', max_length=128),
        ),
    ]
