import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import Providers from "@/components/providers/providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "useBrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-background antialiased")}>
        <Providers>
          <div className="min-h-screen">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
